name: ocr_text
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed: ^1.0.0
  freezed_annotation: ^1.0.0
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.6
  camera: ^0.9.4+22

  path_provider: ^2.0.11
  google_mlkit_text_recognition: ^0.4.0
  hooks_riverpod: ^1.0.0
  flutter_native_image: ^0.0.6+1
  device_info_plus: ^3.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.0
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
